### PR TITLE
Add `Enumerable#sum`

### PR DESCRIPTION
**Pull request by leviongit**
Thanks to @togetherbeer who benchmarked (and put forward) the idea of this addition

### CODE REVIEW

**Comment by togetherbeer** [comment]
Benchmark times and code
image

<details>
<summary>Code</summary>

```ruby
module Enumerable
  def fn_add_sum
    $fn.add(self)
  end

  def for_sum
    i = 0
    for v in self
      i += v
    end
    i
  end

  def for_sum_double
    i = 0
    for v in self
      i += v*2
    end
    i
  end

  def while_sum
    i = 0
    total = 0
    len = length
    while i < len
      total += self[i]
      i += 1
    end
    total
  end

  def block_for_sum(&blk)
    blk ||= -> v { v }
    total = 0
    for v in self
      total += blk[v]
    end
    total
  end

  def block_for_sum_with_branch(&blk)
    total = 0
    if blk
      for v in self
        total += blk[v]
      end
    else
      for v in self
        total += v
      end
    end
    total
  end

  def block_while_sum_with_branch(&blk)
    total = 0
    i = 0
    len = length
    if blk
      while i < len
        total += blk[self[i]]
        i += 1
      end
    else
      while i < len
        total += self[i]
        i += 1
      end
    end
    total
  end

  def empty_method
  end
end

def bench_sum
  array = (1..100).to_a.shuffle

  bench! warmup: -> { array.each { |v| v*2 } },
    empty_method: -> { array.empty_method },
    for_sum: -> { array.for_sum },
    for_sum_double: -> { array.for_sum_double },
    while_sum: -> { array.while_sum },
    fn_add_sum: -> { array.fn_add_sum },
    block_for_sum_no_block: -> { array.block_for_sum },
    block_for_sum_identity: -> {
      array.block_for_sum { |v| v }
    },
    block_for_sum_double: -> {
      array.block_for_sum { |v| v*2 }
    },
    block_for_sum_with_branch_no_block: -> { array.block_for_sum_with_branch },
    block_for_sum_with_branch_identity: -> {
      array.block_for_sum_with_branch { |v| v }
    },
    block_for_sum_with_branch_double: -> {
      array.block_for_sum_with_branch { |v| v*2 }
    },
    block_while_sum_with_branch_no_block: -> { array.block_while_sum_with_branch },
    block_while_sum_with_branch_identity: -> {
      array.block_while_sum_with_branch { |v| v }
    },
    block_while_sum_with_branch_double: -> {
      array.block_while_sum_with_branch { |v| v*2 }
    }
end
```
</detail>

**Comment by amirrajan** [comment]
try benchmarking `fn.each`

```ruby
fn.each some_array do |i| 
end
```

**Comment by togetherbeer** [comment]
image

```ruby
  def fn_each_sum_with_branch(&blk)
    total = 0
    if blk
      fn.each(self) { |v| total += blk[v] }
    else
      fn.each(self) { |v| total += v }
    end
    total
  end
  ```

**Comment by leviongit** [comment]
It sure seems that while is still faster

**Pull request merged**
