### PR TITLE
Update inputs.rb

### PR DESCRIPTION
**Pull request by phaedryx**
not sure about the method name

### CODE REVIEW

**Comment by amirrajan** [comment]
What's the motivation of this? Context of how it's being used?

**Comment by phaedryx** [comment]
Context of what keys are being pressed and what their values are. The `truthy_keys` is a randomly ordered (because: hash) array so you have to be careful how you parse it.

Also, makes it easier to check keys, e.g. check if 'f' is pressed:

`if ...truthy_keys.include?('f'.to_sym)`
v.s
`if ...truthy_keys_hash['char'] == 'f'`

or answer "which key was pressed?"

`(...truthy_keys - [:char, :raw_key, :shift, :meta, etc]).to_s`

vs.

`...truthy_keys_hash['char']`

**Comment by amirrajan** [comment]
Just need some clarification on the order/why it's important. This works

```
if thruthy_keys.include? :f 
end
```

For the specific key, you have `args.inputs.keyboard.key_down.char` and (if you want to go really low level) `args.inputs.keyboard.key_down.raw_key`.

**Comment by phaedryx** [comment]
that works for me

**Pull request closed without merging**
