### PR TITLE
Make local vars and methods persist in the console

### PR DESCRIPTION
**Pull request by awfulcooking**
This change saves local variables created in the console session so they are accessible to future commands.

By instance_eval'ing on the top-level object, methods defined by the user will also remain accessible, due to existing as instance methods on $top_level's singleton.

I've been using this successfully for about a week or so now.

Thanks :-)

### CODE REVIEW

**Comment by togetherbeer** [comment]
`_` will also refer to the result of the last command, like in irb.

**Comment by togetherbeer** [comment]
So when I looked back at this last night chatting to Amir, I realised the description of why it does the top-level instance eval was very opaque.

The reason is that makes it like code eval like it does in irb, and at the top level of scripts.

It is functionally equivalent to Kernel.eval, but a more logical place to execute code from the REPL as it aligns the default context with that of our programs

I don't know why `def foo; end' to Kernel.eval doesn't define methods on Kernel, that may be an implementation detail of DragonRuby.

But that's okay, because an explicit $top_level.instance_eval works as expected, and lets us use methods we define in the REPL in later commands.

Also, it means that you can override your top-level methods from the console.

Say you have a function like ```ruby
def attacking?
  $state.player.can_attack and inputs.keyboard.c
end

def tick args
end
```

You want to test a different implementation during the game..

`def attacking?; something i, want, to, test, quick, on, the, repl; end`

When using [Maw's Tick](https://github.com/togetherbeer/maw/blob/40094ce9562719864e96b7653fb8db07b56355d7/lib/maw.rb#L36), it means you can try out a new tick function right from the command line!

`tick { do_this_instead; now_that }`

**Comment by togetherbeer** [comment]
(There is a dependency loop in GTK's tick method resolution that gets the engine confused if you  `def tick args; ;end` at the top level.. not sure exactly what happens but it sticks in an infinite loop.. the console hangs etc too. Somehow the args.* methods that Maw copies to the top level stops this and works as expected)

**Comment by togetherbeer** [comment]
(Amir! Amir! Pls merge me!)

Huh?! Who said that!!?!

**Comment by amirrajan** [comment]
This has been merged into DR's main repo.... better late than never ^_^

**Pull request closed without merging**
