### PR TITLE
Community Documentation Update

### PR DESCRIPTION
**Pull request by MMathew93**
- Fixed collapsible drop downs for side menu
- Added additional submenus for sub items

### CODE REVIEW

**Comment by kfischer-okarin** [comment]
Looks good, but I fear just updating the HTML will not do the trick.

You have to update this code as well - since this generates the HTML files:
https://github.com/DragonRuby/dragonruby-game-toolkit-contrib/blob/master/dragon/docs.rb#L252

Since otherwise your changes will be gone with the next release

**Comment by kfischer-okarin** [comment]
@amirrajan BTW Why are HTML and TXT outputs checked in in the first place? Since you can generate them isn't it redundant to check them in??

**Comment by MMathew93** [comment]
> Looks good, but I fear just updating the HTML will not do the trick.
> 
> You have to update this code as well - since this generates the HTML files: https://github.com/DragonRuby/dragonruby-game-toolkit-contrib/blob/master/dragon/docs.rb#L252
> 
> Since otherwise your changes will be gone with the next release

Oh shoot you are right, my mistake on that. I'll look through the file and see what I can do to get the changes to be added to the  docs and not just in the HTML like a goober. I'll close this out now!

**Comment by DSchaedler** [comment]
Not a goober, my mistake for making it seem like the .html file was the only one that needed updating

**Pull request closed without merging**
