### PR TITLE
Clear console with Control-c

### PR DESCRIPTION
**Pull request by awfulcooking**
Allows the console to be cleared with Control-c

### CODE REVIEW

**Comment by kfischer-okarin** [comment]
This is already possible with Control-g (and Escape as it seems) ;)

If Adding Control C to the bunch is a good idea, then probably better add it to the existing method:

https://github.com/DragonRuby/dragonruby-game-toolkit-contrib/blob/master/dragon/console.rb#L430-L433

**Comment by awfulcooking** [comment]
Aha, I didn't see that :-). I'll change the patch.

**Comment by awfulcooking** [comment]
To make the case for Control-c.. I think it's a natural reflex for many, reusing the muscle memory from IRB, Bash, Python & other interpreters

**Comment by amirrajan** [comment]
Not compatible for Windows users (ctrl-c is "copy" ctrl-p is "paste").

**Comment by awfulcooking** [comment]
Fair thought. Ctrl-c is copy on Linux also, but not in the context of a console / REPL. Ctrl-c will cancel the current input on a Windows cmd or PS session, too, so the same expectation may apply. Selecting text then right clicking is used to copy on Windows command prompts.

**Pull request closed without merging**
