### PR TITLE
Add left/right cursor movement to the console

### PR DESCRIPTION
**Pull request by kfischer-okarin**
Here's left/right cursor movement for the console. Sorry I got caught up in the control/meta issue so I didn't send this PR even though it was already ready for at least a month

### CODE REVIEW

**Comment by amirrajan** [comment]
Mind rebasing T_T

**Comment by kfischer-okarin** [comment]
Done :)

**Comment by amirrajan** [comment]
I'm sorry to do this to you.... can you fix merge conflicts? 😬

**Comment by kfischer-okarin** [comment]
@amirrajan Done!

**Pull request merged**
