### PR TITLE
Add favicon generation to docs.rb for docs.html.

### PR DESCRIPTION
**Pull request by cbilski**
Erquint suggested we add a favicon.  It's embedded as base64, so we don't need an extra ico file floating around.

### CODE REVIEW

**Review by Erquint — CHANGES_REQUESTED** [review]
The only problem I see with this so far is bloating a code file with *binary* data.
I'd suggest separating it into its own file to be `require`d, honestly.

**Comment by cbilski** [comment]
I feel like either way would be fine.  Currently, It's a text-encoding of a binary-ico.  With this implementation, the programmer using docs.rb gets all functionality in one file.  They do not have to also require docs_resources.rb.

It prioritizes usability and removes the need to manage an external ico file at a slight readability cost.

**Comment by cbilski** [comment]
Moved base64 data into separate file after addition discussion in discord.

**Comment by cbilski** [comment]
Additional feedback incorporated.

**Review by Erquint — APPROVED** [review]
Looks good to me.

I suggested the `&` in `Docs&.const_defined?` previously but, as @cbilski pointed out to me in private conversation, it isn't doing anything here. My bad.

And really, thinking of the cases, I doubt that requirement check will ever be needed.
But no harm done either way.

@amirrajan take a look?

**Comment by kfischer-okarin** [comment]
> so we don't need an extra ico file floating around.

I think just having an ico file floating around would be the simplest solution in this case....

**Comment by cbilski** [comment]
> > so we don't need an extra ico file floating around.
> 
> I think just having an ico file floating around would be the simplest solution in this case....

I've seen these docs on the web, and I didn't want to have to think about "what's the web file structure look like for pathing?" or "what if the file structure changes?"  As an embedded resource, it works anywhere: filesystem or webserver.

**Comment by amirrajan** [comment]
Make it a plain old file and put it inside `./docs`

**Comment by cbilski** [comment]
Added ICO to docs.  Removed base64 resource code.

**Comment by amirrajan** [comment]
Added in version `2.10`.

**Pull request closed without merging**
